Added subcommand to simply ask whether a given printer is supported
michaelrsweet/pappl pull request #171
Opened 2021-07-03 10:20 UTC by Bhavna2020

This fixes issue #158.

2021-07-05 22:07 UTC, michaelrsweet requested changes
Please add support for the "device-id" option to the "drivers" sub-command.

2021-07-05 22:07 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +  if (!system_cb)
The system callback doesn't need to be set - look at the code for the drivers sub-command...

2021-07-05 22:07 UTC, michaelrsweet commented on pappl/mainloop.c
> +    "is-supporting",
I would prefer to see this become part of the "drivers" sub-command.

2021-07-06 09:08 UTC, closed without merging

2021-07-06 10:24 UTC, Bhavna2020 commented
OK.