added printer-service-contact-col implementation...
michaelrsweet/pappl pull request #222
Opened 2022-10-17 20:13 UTC by wifiprintguy

but without all of the reformatting that I did because I use different tab stops than Mike does, and I didn't want to annoy him. 😊

2022-10-19 04:59 UTC, wifiprintguy commented
Found a blog with a tutorial on how to retroactively sign Git commits so did that here

2022-10-19 10:33 UTC, michaelrsweet requested changes
Mainly indentation/editorial stuff.

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +    if (!ra || cupsArrayFind(ra, "printer-service-contact-col"))
OK, so I think it would be better to simply look at the members of the structure (`printer->service_contact.name[0]`) to determine whether to return a collection value or `IPP_TAG_UNKNOWN` out-of-band value.

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer-accessors.c
> +// This function sets the printer's contact information.
This needs to be updated ("printer-service-contact", service contact) with a short explanation why the service contact is different from the regular contact.

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +    pappl_contact_t service_contact;            // printer-service-contact-col value (EPX)
Indentation

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +        { "printer-service-contact-col",        IPP_TAG_BEGIN_COLLECTION, 1 },
Indentation

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +        _papplContactImport(ippGetCollection(rattr, 0), &service_contact);
Indentation

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +    if (do_service_contact)
Indentation

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer-private.h
> +    pappl_contact_t    contact;        // "printer-contact-col" value
Indentation

2022-10-19 10:33 UTC, michaelrsweet commented on pappl/printer.h
> +extern void        papplPrinterSetContact(pappl_printer_t *printer, pappl_contact_t *contact) _PAPPL_PUBLIC;
Indentation

2022-10-20 11:48 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +    if (!ra || cupsArrayFind(ra, "printer-service-contact-col"))
Don't bother creating the collection unless you'll use it - just move the "ipp_t *col" into the "else" clause.

2022-10-26 22:00 UTC, wifiprintguy commented
Will re-engage on this once pull request #223 is completed and either approved or rejected

2023-01-06 16:18 UTC, wifiprintguy commented
Withdrawing this PR since I have a more recent one that covers all work to date minus my inappropriate formatting changes

2023-01-06 16:18 UTC, closed without merging