adding basic printer description attributes
michaelrsweet/pappl pull request #223
Opened 2022-10-19 03:02 UTC by wifiprintguy

using a patchfile from a diff from the epx-prototype branch on this one file because I cannot figure out the cherry-pick syntax and am doing it the hard way

2022-10-19 05:00 UTC, wifiprintguy commented
Found a blog with a tutorial on how to retroactively sign Git commits so did that here

2022-10-19 10:21 UTC, michaelrsweet requested changes
Good first pass, mostly editorial changes needed.

2022-10-19 10:21 UTC, michaelrsweet commented on pappl/printer.c
> +
I'd prefer not to have "EPX 2.0" comments here with the extra separating whitespace. Also, the current implementation of the cupsHashData function in libcups only supports the `sha2-` algorithms and not the `sha3-` or `shake-` algorithms, so they shouldn't be listed here. Finally, indentation should be *2* spaces, not 4.

2022-10-19 10:21 UTC, michaelrsweet commented on pappl/printer.c
> +    //-----------------------------------------------------------------------------------
Ditto here about EPX comments and extra whitespace.

Additionally, I do try to sort the attributes since it helps to speed up filtering with "requested-attributes", so please move these around to appear inline with the other existing attributes.

2022-10-19 10:21 UTC, michaelrsweet commented on pappl/printer.c
> +    ippAddString(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_TEXT), "printer-detailed-status-messages", NULL, "TODO: HOOK ME UP TO SOMETHING"); // TODO: Hook this up to something that repo
Since this is Printer Status attribute, this should be in `_papplPrinterCopyAttributes`. And honestly there is nothing we'd be filling in here except maybe a history buffer of prior printer errors (i.e. capture `papplLogPrinter` errors).

2022-10-19 19:32 UTC, wifiprintguy commented
I think I resolved all the issues with 2 additional commits. let me know if I need to do more.

2022-10-20 11:44 UTC, michaelrsweet requested changes
Better, but still some nits...

2022-10-20 11:44 UTC, michaelrsweet commented on pappl/printer.c
> +  ippAddString(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-password-repertoire-configured", NULL, "iana_utf-8_any");
This should be a settable member of `pappl_printer_t` that is reported in `_papplPrinterCopyAttributes`, and should internally be an enum that is mapped to the strings.

2022-10-20 11:44 UTC, michaelrsweet commented on pappl/printer.c
> +  ippAddString(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-release-action-default", NULL, "none");
The default needs to be part of `pappl_printer_t` and reported in `_papplPrinterCopyAttributes`. Also, I've been using enums at the API level and mapping to strings at the last minute...

2022-10-20 11:44 UTC, michaelrsweet commented on pappl/printer.c
> +  // proof-copies-supported
Looking more closely at the existing code, I think we need to make this conditional based on copy support - see how the "copies-supported" attribute is handled in `_papplPrinterCopyAttributes`.

2022-10-20 16:47 UTC, wifiprintguy commented on pappl/printer.c
> +    "none",
I was thinking it was necessary to do so to satisfy the prototyping requirement for the EPX spec.

2022-10-20 17:24 UTC, wifiprintguy commented on pappl/printer.c
> +  ippAddInteger(printer->attrs, IPP_TAG_PRINTER, IPP_TAG_INTEGER, "job-cancel-after-default", 900); // 15 minutes
should the value be set from a new field in _pappl_printer_s, like "cancel_after"?

2022-10-20 18:41 UTC, michaelrsweet commented on pappl/printer.c
> +  ippAddInteger(printer->attrs, IPP_TAG_PRINTER, IPP_TAG_INTEGER, "job-cancel-after-default", 900); // 15 minutes
Yes

2022-10-20 18:45 UTC, michaelrsweet commented on pappl/printer.c
> +    "none",
I think it is sufficient to show that it works for one, since the spec doesn't require support for all actions, and the attribute itself is only conditionally required (condition not specified, but I assume for Printers that support Job Release).

From an implementation standpoint, any of these can be supported through the web interface. But longer term I'd want to hook this up to the printer driver data so the driver can indicate which methods are natively supported by the printer.

2022-10-23 21:04 UTC, wifiprintguy commented on pappl/printer.c
> +    "none",
I will start with 'button-press' and add the others later if I get a bee in my bonnet

2022-10-23 21:08 UTC, wifiprintguy commented on pappl/printer.c
> +  ippAddStrings(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-password-encryption-supported", (int)(sizeof(job_password_encryption) / sizeof(job_password_encryption[0])), NULL
Presumably this is also true for the line for "job-password-repertoire-supported" and "job-release-action-supported"?

2022-10-23 21:23 UTC, michaelrsweet commented on pappl/printer.c
> +  ippAddStrings(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-password-encryption-supported", (int)(sizeof(job_password_encryption) / sizeof(job_password_encryption[0])), NULL
Yes

2022-10-23 21:39 UTC, wifiprintguy commented on pappl/printer.c
> +  ippAddString(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-password-repertoire-configured", NULL, "iana_utf-8_any");
These enums can be consecutive integer values, not bits for a bitfield, so I'll add them that way. Do you want a "none" value mapped to 0 (zero)?

2022-10-24 00:13 UTC, michaelrsweet commented on pappl/printer.c
> +  ippAddString(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-password-repertoire-configured", NULL, "iana_utf-8_any");
Not all values will be supported by all printers, so we should use the bitfield approach like I do for print-color-mode and other keyword attributes. There are support methods to do the mapping...

2022-10-26 03:42 UTC, wifiprintguy commented on pappl/printer.c
> +  ippAddString(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-release-action-default", NULL, "none");
Maybe "job-sheets-default" needs to similarly be moved into _papplPrinterCopyAttributes()?

2022-10-26 13:27 UTC, michaelrsweet commented on pappl/printer.c
> +  ippAddString(printer->attrs, IPP_TAG_PRINTER, IPP_CONST_TAG(IPP_TAG_KEYWORD), "job-release-action-default", NULL, "none");
Since we don't currently support job-sheets in PAPPL and the only value we report is "none", I don't think we need/want to do that at this time.

Obviously if we add job-sheets/-col support to PAPPL then the default will need to move to `_papplPrinterCopyAttributes` like the others.

2023-01-06 16:19 UTC, closed without merging