Fix listing devices via "devices" subcommand
michaelrsweet/pappl pull request #262
Opened 2023-03-05 20:03 UTC by tillkamppeter

Fixes issue #253

When running a Printer Application (ex. ps-printer-app) as server and doing the client call
```
ps-printer-app devices
```
the use of custom backends (schemes, like "`cups:`" for CUPS backends in pappl-retrofit) was not taken into account, as simply `papplDeviceList()` was called, with neither a system created nor the devices list polled from the running server.

One could create the system before to get the custom scheme definitions in place, but the server is usually running as root and the client doing the request as the calling user. As some backends, independent of being PAPPL's own backends or any custom backends, discover devices only as root, letting the client call producing a different usually incomplete result.

Therefore we do an `IPP_OP_PAPPL_FIND_DEVICES` IPP request to the server to let the server auto-discover the available devices and report back the results.

There is also a bug in the server's `IPP_OP_PAPPL_FIND_DEVICES` (and `IPP_OP_PAPPL_CREATE_PRINTERS`) operation. The device list callback function `_papplDeviceInfoCallback()` returns "`true`" and not "`false`" after outputting an item, making the device listing process stop on the first item. making only the first discovered device listed (or only the first discovered printer set up). This is also corrected in this commit.

2023-03-05 21:20 UTC, michaelrsweet requested changes
Generally I like this, just needs some cleanup.

2023-03-05 21:20 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +    int num_devices = ippGetCount(attr);
Needs to be `cups_len_t` since CUPS 3.x uses `size_t` while CUPS 2.x uses `int`. Also please add a comment describing the variable...

2023-03-05 21:20 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +    for (int i = 0; i < num_devices; i ++)
Prefer to declare loop variable outside the `for` loop (yes I know C99 allows it but then you don't get to document what "i" is...) Also it needs to be `cups_len_t`...

2023-03-05 21:20 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +      ipp_t* item = ippGetCollection(attr, i);
Comments for each variable, should be `ipp_t *item` (space before "*" and not after).

2023-03-05 21:20 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +      ipp_attribute_t *item_attr;
Also comments for these plus use tabs to align "*name".

"str" might be better "device_uri" (more descriptive)...

2023-03-05 21:20 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +      if ((item_attr = ippFindAttribute(item, "smi55357-device-uri", IPP_TAG_ZERO)) != NULL &&
This can all be on one line, and "str" cannot be `NULL` so maybe don't even worry about assigning to a variable and just `puts(ippGetString(item_attr, 0, NULL);`...

2023-03-05 21:20 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +	      (str = ippGetString(item_attr, 0, NULL)) != NULL)
Again, the string cannot be `NULL` if the attribute isn't `NULL`. Another common code pattern I use is `if ((variable = ippGetString(ippFindAttribute(item, "bla", IPP_TAG_ZERO), 0, NULL)) != NULL)`.

2023-03-05 21:20 UTC, michaelrsweet commented on pappl/mainloop-subcommands.c
> +  else if (cupsLastError() != IPP_STATUS_ERROR_NOT_FOUND)
You already checked `cupsLastError` before, so if there is no attribute there are no devices (and PAPPL will return an IPP error which you handle above...)

2023-03-05 22:36 UTC, tillkamppeter commented on pappl/mainloop-subcommands.c
> +    int num_devices = ippGetCount(attr);
Done.

2023-03-05 22:36 UTC, tillkamppeter commented on pappl/mainloop-subcommands.c
> +    for (int i = 0; i < num_devices; i ++)
Done.

2023-03-05 22:37 UTC, tillkamppeter commented on pappl/mainloop-subcommands.c
> +      ipp_attribute_t *item_attr;
Done (`str` removed, see below).

2023-03-05 22:40 UTC, tillkamppeter commented on pappl/mainloop-subcommands.c
> +      ipp_t* item = ippGetCollection(attr, i);
Done.

2023-03-05 22:40 UTC, tillkamppeter commented on pappl/mainloop-subcommands.c
> +      if ((item_attr = ippFindAttribute(item, "smi55357-device-uri", IPP_TAG_ZERO)) != NULL &&
Done.

2023-03-05 22:41 UTC, tillkamppeter commented on pappl/mainloop-subcommands.c
> +	      (str = ippGetString(item_attr, 0, NULL)) != NULL)
Done as in your previous comment.

2023-03-05 22:41 UTC, tillkamppeter commented on pappl/mainloop-subcommands.c
> +  else if (cupsLastError() != IPP_STATUS_ERROR_NOT_FOUND)
Done.

2023-03-07 12:51 UTC, michaelrsweet approved these changes

2023-03-07 12:52 UTC, merged