printer-driver.c: Fix crash when adding generic PS printer
michaelrsweet/pappl pull request #322
Opened 2024-01-19 14:35 UTC by zdohnal

If legacy-printer-app is run for the first time and generic PS driver was chosen when installing the printer, the application crashes during adding the printer.

It is because the printer structure does not have device_id set, and the library tries to get data from already freed `printer->driver_attrs`. Additionally, if the device id exists in the printer, it rewrites incorrect structure (we should set device id attr in `attrs`, which we return).

The fix adds possibility to extract device id from `printer->attrs` and if device id is missing in `printer->attrs` and `document-format-supported` as well, try `document-format-default` and if this attribute is missing, return NULL.

2024-01-19 14:37 UTC, zdohnal commented
The key for reproducing the issue is that it must be the first run of legacy-printer-app after its installation and start. I was not able to reproduce in other runs.

2024-01-19 16:33 UTC, michaelrsweet commented
Hard to diagnose this without a backtrace...

2024-01-19 16:35 UTC, michaelrsweet requested changes
Need more information before we can decide this is an appropriate set of fixes.

2024-01-19 19:18 UTC, zdohnal commented
[Full backtrace of the crash](https://github.com/zdohnal/pappl-retrofit/blob/fedora-package/gdb-bt) - the program crashes in libcups, because it tries to access invalid memory.

2024-01-22 19:21 UTC, michaelrsweet requested changes
OK, I've had a chance to go through this and yes there are a couple bugs here but the fixes you've proposed aren't quite right. I'll be pushing the correct fixes shortly to both the master and v1.4.x branches. But thank you for catching this!

2024-01-22 19:21 UTC, michaelrsweet commented on pappl/printer-driver.c
> +  else if ((attr = ippFindAttribute(printer->attrs, "printer-device-id", IPP_TAG_PRINTER)) != NULL)
After looking through this, we don't want to look for printer-device-id in `printer->attrs` since it shouldn't be there and you'd end up with duplicate printer-device-id attrs.

2024-01-22 19:21 UTC, michaelrsweet commented on pappl/printer-driver.c
> +    if ((formats = ippFindAttribute(printer->attrs, "document-format-supported", IPP_TAG_MIMETYPE)) == NULL)
This should just be looking in attrs since printer->attrs won't have document-format-supported (driver-specific) and we just want document-format-supported since document-format-default is just the one default and usually application/octet-stream.

2024-01-22 20:37 UTC, michaelrsweet commented
[master 47cfc65] Fix printer-device-id (Issue #322)

[v1.4.x 8820820] Bump version/copyright.

2024-01-22 20:37 UTC, closed without merging

2024-01-23 17:03 UTC, zdohnal commented
Thank you for the fix, Mike! It works in my testing env.