Fixes for issues reported by OpenScanHub
michaelrsweet/pappl pull request #335
Opened 2024-02-08 19:40 UTC by zdohnal

2024-02-08 21:38 UTC, michaelrsweet requested changes
See comments.

2024-02-08 21:38 UTC, michaelrsweet commented on pappl/job-accessors.c
> +  if (job->state == state)
I'd prefer to have this be `!=` and put the state change code in the block, rather than adding another exit point from the function...

2024-02-08 21:38 UTC, michaelrsweet commented on pappl/job.c
> +  _papplRWLockRead(job->system);
This change isn't necessary.

2024-02-08 23:35 UTC, michaelrsweet commented
[v1.4.x 7fd86e1] Fix some issues discovered by OpenScanHub (Issue #335)

2024-02-08 23:35 UTC, closed without merging

2024-02-09 06:07 UTC, zdohnal commented on pappl/job-accessors.c
> +  if (job->state == state)
I've caught this habit from times when I wrote code for a python project - in the end I liked how simple and straight the final code is, instead of closing it in another block.
I can think of a disadvantage being that you have to unlock/free any relevant memory at every exit point. Is there other disadvantage or is it a matter of habit in person's code style?

2024-02-09 06:43 UTC, zdohnal commented on pappl/job.c
> +  _papplRWLockRead(job->system);
I've looked into the code more deeply and now I see why it is not necessary - FTR for myself and others - guarding job->format there is unnecessary - every function which calls this function creates its own instance of job, so there are no threads which would change format for the same job at the moment.

2024-02-09 11:40 UTC, michaelrsweet commented on pappl/job-accessors.c
> +  if (job->state == state)
@zdohnal If there is no cleanup needed, I do a return (like for the "job" NULL check). But when you have lock (or other) cleanup I either use code blocks or "goto" to make sure that a) I don't have a lot of duplicate code that I have to keep in sync and b) I fully understand the implications of whatever recovery a particular piece of code requires.