client-auth.c: Fix authentication denial for valid logins
michaelrsweet/pappl pull request #342
Opened 2024-02-15 16:59 UTC by zdohnal

According man pages, `getgrouplist()` always return non-zero number, so we have to handle only the case when user is in more groups than we have static array for.

2024-02-16 13:51 UTC, michaelrsweet commented
From the getgrouplist man page on my Mac:

```
RETURN VALUES
     The getgrouplist() function returns 0 on success.  If the size of the
     group list is too small to hold all the user's groups, getgrouplist()
     returns -1 to indicate failure.  In this case, the group array will be
     filled with as many groups as will fit.
```

OpenBSD's implementation seems to match macOS:

```
RETURN VALUES

The getgrouplist() function returns 0 if successful and -1 if the size of the group list is too small to hold all the user's groups. Here, the group array will be filled with as many groups as will fit.
```

But glibc's implementation is different:

```
RETURN VALUE

       If the number of groups of which user is a member is less than or
       equal to *ngroups, then the value *ngroups is returned.

       If the user is a member of more than *ngroups groups, then
       getgrouplist() returns -1.  In this case, the value returned in
       *ngroups can be used to resize the buffer passed to a further
       call to getgrouplist().
```

The fact that you are seeing issues with 32 groups means we need to increase the size of that array, too.

2024-02-16 13:57 UTC, michaelrsweet requested changes
Go ahead and increase the size of the "groups" array to 256 elements.

2024-02-16 13:57 UTC, michaelrsweet commented on pappl/client-auth.c
> +	      papplLogClient(client, PAPPL_LOGLEVEL_WARN, "User in too many groups: '%s', cutting to 32", username);
We need a better message here, and one that doesn't hardcode the limit. Something like: "User '%s' is in %d groups but only support up to %d groups."

2024-02-16 13:57 UTC, michaelrsweet commented on pappl/client-auth.c
>  	    if (getgrouplist(username, (int)user->pw_gid, groups, &num_groups))
For consistency, add a "< 0" to the condition here.

2024-02-16 13:57 UTC, michaelrsweet commented on pappl/client-auth.c
> +	    if (getgrouplist(username, user->pw_gid, groups, &num_groups) == -1)
Make this "< 0" instead of comparing to -1.

2024-02-19 14:09 UTC, zdohnal commented
> But glibc's implementation is different:
> 
> ```
> RETURN VALUE
> 
>        If the number of groups of which user is a member is less than or
>        equal to *ngroups, then the value *ngroups is returned.
> 
>        If the user is a member of more than *ngroups groups, then
>        getgrouplist() returns -1.  In this case, the value returned in
>        *ngroups can be used to resize the buffer passed to a further
>        call to getgrouplist().
> ```
> 
> The fact that you are seeing issues with 32 groups means we need to increase the size of that array, too.

We can do that too for sure, but the issue was with the condition - the function probably returns 0 only when user would not be in any group (IMHO it is not possible, if the user exists, so it is not mentioned in man page), so it returned non-zero for my user (positive number of groups, since I'm not in more than 32 groups), so the execution got into the if scope and returned failure.

2024-02-20 16:30 UTC, zdohnal commented on pappl/client-auth.c
> +	      papplLogClient(client, PAPPL_LOGLEVEL_WARN, "User in too many groups: '%s', cutting to 32", username);
Updated to "User '%s' is in %d groups - supported up to %d groups.", using local constant _PAPPL_MAX_GROUPS. The same constant is used for declaration of array.

2024-02-20 16:49 UTC, michaelrsweet requested changes
See comments. We obviously need to do something here but need to be careful because getgrouplist is not POSIX.

2024-02-20 16:49 UTC, michaelrsweet commented on pappl/client-auth.c
> +#define _PAPPL_MAX_GROUPS	32	// Maximum number of groups user can be member of
Don't bother with a constant since it is used in one place.

2024-02-20 16:49 UTC, michaelrsweet commented on pappl/client-auth.c
> +      int	groups[_PAPPL_MAX_GROUPS];		// Authenticated groups, if any
Make these `[128]`.

2024-02-20 16:49 UTC, michaelrsweet commented on pappl/client-auth.c
> +	      papplLogClient(client, PAPPL_LOGLEVEL_WARN, "User '%s' is in %d groups - supported up to %d groups.", username, num_groups, _PAPPL_MAX_GROUPS);
Since only glibc sets num_groups to a larger value, just sat "User '%s' is in more than %d groups." and use `(int)(sizeof(groups) / sizeof(groups[0]))`.

2024-02-20 16:49 UTC, michaelrsweet commented on pappl/client-auth.c
> +	      num_groups = _PAPPL_MAX_GROUPS;
Make this conditional for glibc:

```c
#  ifdef __GLIBC__
        // glibc's getgrouplist implementation sets  num_groups to the total number of groups instead of the number of group stored...
        num_groups = (int)(sizeof(groups) / sizeof(groups[0]);
#  endif // __GLIBC__
```

2024-02-21 15:56 UTC, zdohnal commented on pappl/client-auth.c
>  	    if (getgrouplist(username, (int)user->pw_gid, groups, &num_groups))
Done.

2024-02-21 15:57 UTC, zdohnal commented on pappl/client-auth.c
> +	      papplLogClient(client, PAPPL_LOGLEVEL_WARN, "User '%s' is in %d groups - supported up to %d groups.", username, num_groups, _PAPPL_MAX_GROUPS);
Applied, thanks!

2024-02-21 15:58 UTC, zdohnal commented on pappl/client-auth.c
> +      int	groups[_PAPPL_MAX_GROUPS];		// Authenticated groups, if any
Ok, just as I mentioned - the auth did not fail because I'm in too many groups, but due it returned number of groups where I'm in.

2024-02-21 16:00 UTC, zdohnal commented on pappl/client-auth.c
> +	      num_groups = (int)(sizeof(group) / sizeof(groups[0]));
Fixed.

2024-02-21 16:01 UTC, zdohnal commented on pappl/client-auth.c
> +	      num_groups = _PAPPL_MAX_GROUPS;
Applied, thanks! (I should copy+paste...)

2024-02-21 16:14 UTC, michaelrsweet approved these changes

2024-02-21 16:14 UTC, merged

2024-02-22 07:11 UTC, zdohnal commented
@michaelrsweet the message in Changelog is incorrect - it was not issue about user being in more than 32 groups. Auth failed if user was in any group (the function returned number of groups he's in) with glibc.