dnssd.c: Enable service registration on loopback only
michaelrsweet/pappl pull request #346
Opened 2024-02-29 09:36 UTC by zdohnal

In case users would like to prevent sharing services from printer
 applications to local network, restrict it to localhost and let CUPS
 do the sharing.

This can be done by setting listen-hostname in PAPPL API - this prevents accessing the public addresses, but the service is still published on those public addresses. This can be prevented if the machine hostname is changed to localhost, but that's not desired on machines IIUC.

The PR does the following:

- introduced new pappl system member reghost, which is used for saving listen-hostname,
- new public accessors for that member, papplSystemSetRegHostName() and papplSystemGetRegHostName() - user can set the member to localhost or to the current hostname
- dnssd functions will check this member, and if it is localhost, it will use loopback index
- in case of Avahi it passes NULL as hostname to let Avahi decide what hostname to use (in case of hostname conflicts - and Avahi forbids using localhost if it is not FQDN)

The result is that if reghost is set to localhost, the service is published on .local address, but resolved to loopback because CUPS uses DNS-SD names in URIs.

PAPPL 2.x version requires CUPS PR https://github.com/OpenPrinting/cups/pull/902 to have it working.

2024-03-01 13:51 UTC, michaelrsweet requested changes
I'm not comfortable separating the "registration hostname" from the "listen hostname".

I support changing things to correctly advertise for the loopback interface but not for separating the hostname configurations.

2024-03-06 06:51 UTC, zdohnal commented
@michaelrsweet 

> I'm not comfortable separating the "registration hostname" from the "listen hostname".
> 

Hmm... I meant registration hostname to be exactly the listen hostname - and we have to save the 'listen hostname' somewhere to have a way how to decide which net interface to use for advertising, because ```papplSystemAddListeners()``` saves only ports and socket fds, and ```system->hostname``` serves different purpose (setting machine's hostname).

With your feedback, I guess you mean I can save the listen hostname into system struct in ```papplSystemAddListeners()``` instead of having public functions for setting them - if there is no public functions to access them, it prevents possible separation.

> I support changing things to correctly advertise for the loopback interface but not for separating the hostname configurations.

It currently requires changing machine's hostname to change the scope where the service will be advertised - IMO we have to separate server hostname and listen hostname configurations (if you meant them) and have a way where to save listen hostname, or remove the server hostname functionality to change machine's hostname (keep the hostname only internally and do not change /etc/hostname).

WDYT?

2024-03-06 08:14 UTC, zdohnal commented
I've removed public accessors and renamed reghost to listen_hostname - it is set only when ```papplSystemAddListeners()``` is called.

I set the PR to [WIP], until  it is clear how I should change it.

2024-03-06 08:18 UTC, zdohnal commented
@michaelrsweet ad saving listen-hostname - Or did you mean to save listen-hostname into ```system->hostname``` in ```papplSystemAddListeners()```? That's another way how I imagine to keep the hostnames in sync, but I'm not sure if it is a right call (yeah, if I assign the pointer directly without calling accessor ```papplSystemSetHostName()```, the machine's hostname is not changed, so it could work, but I'm not sure if it is correct thing to do there).

2024-03-13 15:47 UTC, zdohnal commented
Ignore the review request for now, I rewrite it to use ```system->hostname```. Once it is ready, I remove the  [WIP].

2024-03-14 08:17 UTC, zdohnal commented
Ready for review.

2024-07-17 07:39 UTC, zdohnal commented
@michaelrsweet ping

2024-07-18 01:32 UTC, michaelrsweet requested changes
Needs work.

2024-07-18 01:32 UTC, michaelrsweet commented on pappl/dnssd.c
> +_papplDNSSDIsLoopback(const char *name)
I'm still not clear why we need a function for this...

2024-07-18 01:32 UTC, michaelrsweet commented on pappl/system-accessors.c
> +
This isn't where I'd save the hostname... You can have multiple listeners.

2024-07-18 01:32 UTC, michaelrsweet commented on pappl/dnssd.c
> +  if_index = _papplDNSSDIsLoopback(system->hostname) ? CUPS_DNSSD_IF_INDEX_LOCAL : CUPS_DNSSD_IF_INDEX_ANY;
I'm thinking we should examine the listeners or keep a boolean to track whether we are listening on an externally accessible address.

2024-07-18 01:32 UTC, michaelrsweet commented on pappl/system.c
> +      if (!_papplDNSSDIsLoopback(system->hostname) && force_dns_sd)
It isn't about being on the loopback interface since we still need to advertise on localhost.

2024-10-15 21:13 UTC, michaelrsweet commented
OK, like the 1.4.x changes I'm pushing back on this. If listenhost is "localhost", then we only advertise on the loopback interface. This is the correct behavior.

2024-10-15 21:13 UTC, closed without merging