Handle cases when auth groups are unset
michaelrsweet/pappl pull request #354
Opened 2024-03-18 16:23 UTC by zdohnal

Currently, pappl based applications require authentication every time for any request if authentication module is set, even if authentication group(s) is set to None.

With this PR, admin can set admin and print group to None. Every admin action is allowed if admin group is None. For printing jobs, Validate-Job, Print-Job, Create-Job are allowed, Send-Document if the requesting client is owner of the job - value of requesting-user-name is used as default value,
 in case authorization field does not contain it.

This allows smooth printing to the printer application via CUPS when printer application uses PAM module to protect against simple attacks.

2024-03-18 17:23 UTC, michaelrsweet requested changes
Needs work.

2024-03-18 17:23 UTC, michaelrsweet commented on pappl/client-ipp.c
> +      if ((attr = ippFindAttribute(client->request, "requesting-user-name", IPP_TAG_NAME)) != NULL)
No, `client->username` is the AUTHENTICATED username, not whatever the client sends in the "requesting-user-name" attribute. There are places where we want to fallback on "requesting-user-name", but this isn't how to do it.

2024-03-18 17:23 UTC, michaelrsweet commented on pappl/client-auth.c
> +  if (_papplSystemGroupIsEmpty(client->system->admin_group) &&
I'm uncomfortable with this change, need to think about the security implications.

2024-03-18 17:23 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +static bool		ipp_is_printing_op(pappl_client_t *client);
No, we don't limit authentication to printing operations.

2024-03-18 17:23 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +  if (_papplSystemGroupIsEmpty(client->printer->print_group) && httpAddrIsLocalhost(httpGetAddress(client->http)) &&
This isn't the place for that sort of detemination.

2024-03-18 17:23 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +static bool					// O - `true` if the operation is related to print job and valid, `false` if not
ALL printers operations except Get-Printer-Attributes MUST be authenticated when the print group is set.

2024-03-18 17:23 UTC, michaelrsweet commented on pappl/system-accessors.c
> +
Empty or NULL group, NOT the "none" group (which is a valid group name and yes people *do* use that name...)

Also, `_papplSystemGroupIsEmpty` implies it operates on a `pappl_system_t` object. Better to have a different name if this is to be generic or provide the equivalent `_papplPrinterXXX` function for the print group.

2024-03-19 12:07 UTC, zdohnal commented on pappl/client-auth.c
> +  if (_papplSystemGroupIsEmpty(client->system->admin_group) &&
AFAIK it has the same implications as the current default in printer applications - any user can do all admin tasks. But I can add check here whether there is an authentication service and move it to ```_papplClientIsAuthorizedForGroup()```.

2024-03-19 12:36 UTC, zdohnal commented on pappl/client-ipp.c
> +      if ((attr = ippFindAttribute(client->request, "requesting-user-name", IPP_TAG_NAME)) != NULL)
Yes, I saw this later in the code - I meant this assignment as a fallback for purpose of this code:

```
 806   if (code == HTTP_STATUS_CONTINUE && client->job && client->job->username && strcmp(client->username, client->job->username))
 807   {
 808     // Not the owner, try authorizing with admin group...
 809     code = _papplClientIsAuthorizedForGroup(client, true, client->system->admin_group, client->system->admin_gid);
 810   }
```

where, even if the user is really owner of the job, ```client->username``` is empty, so the request gets to trying authenticate with admin group (which is kind of off-topic for job related operations IMHO).

What I had in mind is to simulate similar settings as default CUPS has - authentication required for admin tasks, printing operations (except for Send-Document) requires no authentication by default.

Does the fallback make sense in ```_papplClientIsAuthorizedForGroup()``` if we don't find authorization field?

2024-03-19 14:28 UTC, zdohnal commented on pappl/printer-ipp.c
> +static bool		ipp_is_printing_op(pappl_client_t *client);
Ok, now I see the function is combining two things - finding out whether the operation is within the expected set and checking the usernames in case of Send-Document, which should not happen. I basically wanted to simulate the default CUPS behavior for printing related operations, so I implemented it in one function, which was to be used only in this use case.

I've thrown it away for now.

2024-03-19 16:21 UTC, zdohnal commented on pappl/system-accessors.c
> +
> Empty or NULL group, NOT the "none" group (which is a valid group name and yes people _do_ use that name...)

Ok, never knew it exists :D .

> 
> Also, `_papplSystemGroupIsEmpty` implies it operates on a `pappl_system_t` object. Better to have a different name if this is to be generic or provide the equivalent `_papplPrinterXXX` function for the print group.

I've made it ```_papplClientGroupIsEmpty()``` for now, since it is used when authenticating client request (we don't use printer-private.h in client-auth.c).

2024-03-22 13:48 UTC, michaelrsweet requested changes
See comments.

2024-03-22 13:48 UTC, michaelrsweet commented on pappl/client-accessors.c
> +_papplClientGroupIsEmpty(const char *group)	// I - Group name
Also not an operation on a client object. Why not just look for a NULL or empty string?

2024-03-22 13:48 UTC, michaelrsweet commented on pappl/printer-ipp.c
> +  // In case of local connections, use requesting-user-name attribute as username later if client username is missing
No, we want an authenticated username. The alternative (if authentication is enabled) would be to lookup the UID via peer credentials. I don't want to rely on requesting-user-name if authentication is enabled.

2024-10-15 21:00 UTC, closed without merging

2024-10-15 21:00 UTC, michaelrsweet commented
OK, I think with the following change the "None" group should work as expected:

[v1.4.x 1c387a9] Treat blank group name the same as a NULL group name.