system-loadsave.c: Protect state file from world-readable
michaelrsweet/pappl pull request #365
Opened 2024-08-08 18:17 UTC by zdohnal

The state file might include user-sensitive data, we should prevent accessing it from others than owner.

2024-08-08 21:13 UTC, michaelrsweet requested changes
This usage isn't safe. You need to use fchmod right after the file is opened, or wrap the open with umask calls. You also need to not error out if the chmod fails since some filesystems/platforms don't support the operation with all values (think Windows in particular...)

Look at what cupsd does in scheduler/file.c with config/state files...

2024-08-12 11:38 UTC, zdohnal commented
@michaelrsweet thx, I'll look into it!

2024-08-30 09:49 UTC, zdohnal commented
I have found more files which can be protected, so I've added them as well.

2024-09-03 19:07 UTC, michaelrsweet commented on pappl/system-webif.c
> +    if (fchmod(cupsFileNumber(fp), 0600))
A signing request isn't security-critical...

2024-09-04 01:22 UTC, michaelrsweet commented
[master bf52117] Specify restricted permissions for the state file.

The cert/key/csr code is getting overhauled to use the new CUPS X.509 APIs... (#366)

2024-09-04 01:22 UTC, closed without merging